version: "3.8"

services:
  backend:
    build:
      context: ./immudb-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./immudb-backend/.env
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./immudb-fe
      dockerfile: Dockerfile
    ports:
      - "8080:80"

networks:
  default:
    driver: bridge
